name: Deploy to EC2

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check if directory exists
        id: check_directory
        run: |
          if [ -d "./next-app" ]; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi

      - name: Create directory
        run: mkdir -p ./next-app
        if: steps.check_directory.outputs.exists == 'false'

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: next-app
      
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Copy build artifacts to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: ".next/*"
          target: "/var/www/html"

      - name: SSH into EC2 and start app with PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /var/www/html
            npm start
            pm2 start yarn --interpreter bash --name "next-app" -- start